"""Build index.html from toc.json, and anchor the formula sheet so Notes can link its cards.
Run after adding or moving a Note, or editing formula_sheet.html."""
import glob, html, json, re

def title(name):
    m = re.search(r"<title>(.*?)</title>", open(f"{name}.html", encoding="utf-8").read(), re.S)
    return m.group(1).strip() if m else name.replace("_", " ").title()

def build():
    toc = json.load(open("toc.json", encoding="utf-8"))
    listed = {n for m in toc for n in m["notes"]}
    missing = [n for n in listed if not glob.glob(f"{n}.html")]
    if missing:
        raise SystemExit(f"toc.json lists missing Notes: {', '.join(missing)}")
    unsorted = sorted(f[:-5] for f in glob.glob("*.html") if f != "index.html" and f[:-5] not in listed)
    if unsorted:
        toc.append({"module": "Unsorted", "notes": unsorted})

    body = "".join(
        f'<h2>{html.escape(m["module"])}</h2>\n<ol>\n'
        + "".join(f'  <li><a href="{n}.html">{title(n)}</a></li>\n' for n in m["notes"])
        + "</ol>\n"
        for m in toc)
    open("index.html", "w", encoding="utf-8").write(f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>FinMath Notes</title>
<link rel="stylesheet" href="note.css">
</head>
<body>
<h1>FinMath Notes</h1>
<p class="lede">Probability, measure theory &amp; stochastic processes.</p>
{body}</body>
</html>
""")

def anchor_sheet():
    """Give every card and section of formula_sheet.html an id, and dump them to formulas.js
    so note.js can turn "&sect;10.4" into a link with a hover preview of that card."""
    s = open("formula_sheet.html", encoding="utf-8").read()
    s = re.sub(r'<div class="card">(\s*<h4>([\w.]+) )', r'<div class="card" id="\2">\1', s)
    s = re.sub(r'<div class="section-title">(<span class="section-num">(\w+)\.</span>)',
               r'<div class="section-title" id="\2">\1', s)
    open("formula_sheet.html", "w", encoding="utf-8").write(s)
    cards = dict(re.findall(r'<div class="card" id="([^"]+)">(.*?)\n    </div>', s, re.S))
    cards |= {k: f"<h4>{v}</h4>" for k, v in re.findall(r'<div class="section-title" id="(\w+)">(.*?)</div>', s)}
    open("formulas.js", "w", encoding="utf-8").write(
        "// Generated by main.py from formula_sheet.html. Do not edit.\nwindow.FORMULAS = "
        + json.dumps(cards, ensure_ascii=False) + ";\n")
    return cards

if __name__ == "__main__":
    build()
    print("index.html written")
    print(f"formulas.js written ({len(anchor_sheet())} anchors)")
