// Shared MathJax setup for every Note: $…$ inline, $$…$$ display.
window.MathJax = { tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] } };
document.head.appendChild(Object.assign(document.createElement('script'), {
  src: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js', async: true
}));

// Turn "§10.4" / "§12.3–12.5" into links to formula_sheet.html cards, with a hover preview.
// Card contents come from formulas.js, generated by main.py.
document.addEventListener('DOMContentLoaded', () => document.head.appendChild(Object.assign(
  document.createElement('script'), { src: 'formulas.js', onload: linkFormulas })));

function linkFormulas() {
  const F = window.FORMULAS, re = /§\s*([A-Z]?)(\d+(?:\.\d+)?)(?:(\s*[–-]\s*)([A-Z]?)(\d+(?:\.\d+)?))?/g;
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
    acceptNode: n => n.parentElement.closest('a, script, style, mjx-container') || !n.data.includes('§')
      ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT });
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  const link = (key, text) => {
    if (!F[key]) return document.createTextNode(text);
    const a = Object.assign(document.createElement('a'), { href: 'formula_sheet.html#' + key, textContent: text, className: 'fref' });
    a.addEventListener('mouseenter', () => showCard(a, key));
    a.addEventListener('focus', () => showCard(a, key));
    a.addEventListener('mouseleave', hideCardSoon);
    a.addEventListener('blur', hideCardSoon);
    return a;
  };
  for (const n of nodes) {
    const frag = document.createDocumentFragment();
    let last = 0;
    for (const m of n.data.matchAll(re)) {
      const [whole, p1, n1, dash, p2, n2] = m;
      frag.append(n.data.slice(last, m.index), link(p1 + n1, `§${p1}${n1}`));
      if (n2) frag.append(dash, link((p2 || p1) + n2, p2 + n2));
      last = m.index + whole.length;
    }
    frag.append(n.data.slice(last));
    n.replaceWith(frag);
  }
}

let pop, hideTimer;
function showCard(a, key) {
  clearTimeout(hideTimer);
  if (!pop) {
    pop = Object.assign(document.createElement('div'), { className: 'fpop' });
    pop.addEventListener('mouseenter', () => clearTimeout(hideTimer));
    pop.addEventListener('mouseleave', hideCardSoon);
    document.body.appendChild(pop);
  }
  pop.innerHTML = window.FORMULAS[key];
  const r = a.getBoundingClientRect();
  pop.style.left = Math.max(8, Math.min(r.left, innerWidth - pop.offsetWidth - 8)) + 'px';
  pop.style.top = (r.bottom + 6) + 'px';
  pop.hidden = false;
  window.MathJax?.typesetClear?.([pop]);
  window.MathJax?.typesetPromise?.([pop]).then(() => {  // re-flip above the link if it overflows the viewport
    if (r.bottom + 6 + pop.offsetHeight > innerHeight) pop.style.top = Math.max(8, r.top - pop.offsetHeight - 6) + 'px';
  });
}
function hideCardSoon() { hideTimer = setTimeout(() => pop && (pop.hidden = true), 250); }
